//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int examId { get; set; }
        public Nullable<System.DateTime> examDate { get; set; }
        public Nullable<int> examStudentId { get; set; }
        public string examName { get; set; }
    
        public virtual student student { get; set; }
    }
}
