//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class question
    {
        public int questionId { get; set; }
        [Display(Name ="What's the Question ?")]
        [Required(ErrorMessage ="*")]
        public string questionText { get; set; }
        [Display(Name = "Option A")]
        [Required(ErrorMessage = "*")]
        public string optionA { get; set; }
        [Display(Name = "Option B")]
        [Required(ErrorMessage = "*")]
        public string optionB { get; set; }
        [Display(Name = "Option C")]
        [Required(ErrorMessage = "*")]
        public string optionC { get; set; }
        [Display(Name = "Option D")]
        [Required(ErrorMessage = "*")]
        public string optionD { get; set; }
        [Display(Name = "Correct Answer")]
        [Required(ErrorMessage = "*")]
        public string correctAnswer { get; set; }
        [Display(Name = "Select Course")]
        [Required(ErrorMessage = "*")]
        public Nullable<int> questionCourseId { get; set; }
    
        public virtual course course { get; set; }
    }
}
